#!/usr/bin/env python3
"""Write phobos-console's console.yaml from the live cluster -- any number of VM workers / proxies, one globalsc.

Discovery (kubectl get nodes):
  * dilated workers   nodes labelled dilated=true (ins<k>vm), InternalIP 10.2.<n>.2
  * their hypervisors 10.1.<n>.1 (same third octet): the chronos slot-checker components of globalsc
  * proxy node        the first node named proxy-* (the console uses one proxy); its vlan address 10.3.<n>.1
  * globalsc node     the node named globalsc, vlan address 10.4.1.1
  * core node         the first dilated worker (open5gs + DN run there); N6 gateway 10.2.<n>.1
Usage: gen_console_yaml.py <phobos-console dir> <phobos-5g dir> [--numgnb N --numue M]"""
import argparse, json, re, subprocess, sys
from pathlib import Path

ap = argparse.ArgumentParser()
ap.add_argument("console"); ap.add_argument("phobos5g")
ap.add_argument("--numgnb", type=int, default=1); ap.add_argument("--numue", type=int, default=10)
ap.add_argument("--kubectl", default="kubectl")
a = ap.parse_args()

nodes = json.loads(subprocess.check_output(a.kubectl.split() + ["get", "nodes", "-o", "json"]))["items"]
def ip(n):
    return next((x["address"] for x in n["status"]["addresses"] if x["type"] == "InternalIP"), None)
def name(n):
    return n["metadata"]["name"]
dilated = sorted((n for n in nodes if n["metadata"].get("labels", {}).get("dilated") == "true"),
                 key=lambda n: int(re.sub(r"\D", "", name(n)) or 0))
proxies = sorted((n for n in nodes if name(n).startswith("proxy-")), key=lambda n: int(name(n).split("-")[1]))
gsc = [n for n in nodes if name(n) == "globalsc"]
if not dilated or not proxies or not gsc:
    sys.exit(f"cluster incomplete: dilated={len(dilated)} proxies={len(proxies)} globalsc={len(gsc)}")

vm_ips = [ip(n) for n in dilated]
for v in vm_ips:
    if not re.fullmatch(r"10\.2\.\d+\.2", v or ""):
        sys.exit(f"unexpected VM worker address {v} (want 10.2.<n>.2)")
components = [f"10.1.{v.split('.')[2]}.1" for v in vm_ips]            # hypervisor of each dilated VM
proxy_n = int(name(proxies[0]).split("-")[1])
core = dilated[0]
core_n = ip(core).split(".")[2]

console = Path(a.console)
p5g = Path(a.phobos5g)
y = f"""# generated by compute-server scripts/phobos/gen_console_yaml.py -- {len(dilated)} VM workers, {len(proxies)} proxies
cluster:
  kubeconfig: .kubeconfig
  namespace: default
  host_node: globalsc                # real-time side: globalsc pod
  proxy_node: {name(proxies[0])}                # the proxy pod runs here (hostNetwork)
  ssh_key: {Path.home() / '.ssh/id_rsa'}
  ssh_user: ubuntu
phobos:
  repo: {p5g}
  manifests: k8s/local
  proxy_ip: 10.3.{proxy_n + 1}.1
  proxy_control_port: 3600
  proxy_log: /tmp/phobos-k8s/proxy.log
  proxy_log_source: pod
  external_core: open5gs
  local_slotchecker: false
  ue_idle_restart_s: 90
  globalsc:
    ip: 10.4.1.1
    components: [{', '.join(components)}]
  images:
    ran: docker.io/ujjwal1997/phobos-ran:new
    proxy: docker.io/ujjwal1997/phobos-proxy:new
  image_map:
    docker.io/library/phobos-ran:new: docker.io/ujjwal1997/phobos-ran:new
    docker.io/library/phobos-proxy:new: docker.io/ujjwal1997/phobos-proxy:new
    docker.io/library/phobos-dn:iperf3: docker.io/ujjwal1997/phobos-dn:iperf3
  pull_policy: IfNotPresent
  gen_env:
    CORE_DB: {p5g / 'conf/oai_db_1000.sql'}
    UECAP4: {p5g / 'conf/uecap_ports4.xml'}
    CORE_NIC: enp1s0
    CORE_N6_NIC: enp1s0
    N6_GW: 10.2.{core_n}.1
placement:
  core_node: {name(core)}
  gnb_host_network: true
radio_map:
  center: [55.944678, -3.187444]
defaults:
  gnb0_conf: gnb-vnf.conf
  gnbs: {a.numgnb}
  ues: {a.numue}
  split_ues_over_gnbs: true
  admit_interval_slots: 400
  settle_seconds: 60
  ulsch_inactivity: 100
  ue_ports: 1
  trace_level: warn
server:
  host: 0.0.0.0
  port: 8090
  data_dir: data
"""
(console / "console.yaml").write_text(y)
print(json.dumps({"workers": [name(n) for n in dilated], "components": components, "proxy": name(proxies[0]),
                  "core": name(core), "core_ip": ip(core)}))
